# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test
  deploy:
    machine: true
    working_directory: ~/public-repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "67:fc:6f:82:72:5c:a0:6e:d3:3e:f7:72:da:8d:64:e6"
      - run: git config --global user.name "wizardry"
      - run: git config --global user.email "rein1988@gmail.com"
      - run:
        command: git config --global user.email $GH_EMAIL
        command: git config --global user.name $GH_NAME
        command: cd ~/public-repo
        command: ls
      - run:
        command: git clone $CIRCLE_REPOSITORY_URL
        command: git checkout gh-pages || git checkout --orphan gh-pages
        command: cd ~/repo
        command: npm run build
        command: mk build
        command: mv dist/bundle.js ~/public-repo/bundle.js
        command: mv src/html/dbd_log/images ~/public-repo/images
        command: mv src/html/dbd_log/index.html ~/public-repo/index.html
        command: cd ~/public-repo
        command: ls
      - run:
        command: git add -A
        command: git commit --allow-empty
        command: git push origin gh-pages
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
