# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test
  deploy:
    machine: true
    working_directory: ~/public-repo
    steps:
      - run: git config --global user.name "wizardry"
      - run: git config --global user.email "rein1988@gmail.com"
      - run: echo $CIRCLE_BRANCH
      - run: echo $SOURCE_BRANCH
      - run: echo $GH_EMAIL
      - run: echo $GH_NAME
      - run: echo $CIRCLE_REPOSITORY_URL
      - run: echo $CIRCLE_SHA1
      - run: echo $TARGET_BRANCH
      - run:
        command: git config --global user.email $GH_EMAIL
        command: git config --global user.name $GH_NAME
        command: git clone $CIRCLE_REPOSITORY_URL out
        command: cd out
        command: git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
        command: git rm -rf .
        command: cd ..
        command: npm run build
        command: mk build
        command: mv dist/bundle.js ./build/bundle.js
        command: mv src/html/dbd_log/images ./build/images
        command: mv src/html/dbd_log/index.html ./build/index.html
        command: rm -r src dist specs
        command: rm .babelrc .editorconfig .eslintrc.js .prettierignore .stylelintr.json jest.config.js
        command: cp -a build/. out/.
        command: mkdir -p out/.circleci && cp -a .circleci/. out/.circleci/.
        command: cd out
        command: git add -A
        command: git commit --allow-empty
        command: git push origin $TARGET_BRANCH
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
